import type { Metadata } from "next";
import { buildPageMetadata } from "../../lib/site-config";

export async function generateMetadata(): Promise<Metadata> {
  return buildPageMetadata({
    title: "Terms",
    description:
      "Plain-language terms for using archoslabs.xyz, the AI Readiness Assessment, and the Archos Labs consulting offer.",
    path: "/terms",
  });
}

const lastUpdated = "2026-05-08";

export default function TermsPage() {
  return (
    <main className="flex flex-1 flex-col bg-canvas">
      <article className="mx-auto w-full max-w-[760px] px-6 pt-24 pb-32 md:px-12">
        <p className="text-[13px] font-medium uppercase tracking-[0.08em] text-accent">
          Terms
        </p>
        <h1 className="mt-4 text-4xl font-semibold leading-[1.1] tracking-[-0.03em] text-fg md:text-[56px]">
          Terms of use.
        </h1>
        <p className="mt-6 text-[18px] leading-[1.6] text-muted">
          Last updated <time dateTime={lastUpdated}>{lastUpdated}</time>. By
          using <a href="https://archoslabs.xyz" className="text-accent hover:underline">archoslabs.xyz</a>{" "}
          you agree to the terms below. If you do not agree, do not use the
          site.
        </p>

        <h2 className="mt-16 text-2xl font-semibold tracking-[-0.01em] text-fg">
          Who we are
        </h2>
        <p className="mt-4 text-base leading-[1.7] text-muted">
          Archos Labs Pty Ltd is an Australian AI transformation practice and
          product studio. We provide enterprise consulting on data
          architecture, AI readiness, and AI agent development. The website is
          our public face; the consulting work happens under separate
          engagement letters.
        </p>

        <h2 className="mt-16 text-2xl font-semibold tracking-[-0.01em] text-fg">
          What this site is
        </h2>
        <ul className="mt-4 space-y-3 text-base leading-[1.7] text-muted">
          <li>
            Information about our services and how to engage us.
          </li>
          <li>
            The AI Readiness Assessment — a free diagnostic tool that produces
            a written report based on your answers.
          </li>
          <li>
            A way to start a conversation: the contact form and the &ldquo;Book
            a call&rdquo; mailto.
          </li>
        </ul>

        <h2 className="mt-16 text-2xl font-semibold tracking-[-0.01em] text-fg">
          What this site is not
        </h2>
        <ul className="mt-4 space-y-3 text-base leading-[1.7] text-muted">
          <li>
            Not legal, financial, regulatory, or technical advice. Reports and
            articles on this site are general practitioner observations, not
            counsel for your specific situation.
          </li>
          <li>
            Not a substitute for a real consulting engagement. The assessment
            report is a starting point, not a delivered solution.
          </li>
          <li>
            Not a procurement channel. Engagements are governed by signed
            agreements; nothing on this site forms a binding contract for
            services.
          </li>
        </ul>

        <h2 className="mt-16 text-2xl font-semibold tracking-[-0.01em] text-fg">
          Using the assessment
        </h2>
        <p className="mt-4 text-base leading-[1.7] text-muted">
          You can take the AI Readiness Assessment for any organisation you are
          authorised to assess. By submitting answers, you confirm you have
          authority to share that information and that your answers are honest
          to the best of your knowledge. The report we generate is yours to
          use internally — including sharing with colleagues, your CFO, or
          your board.
        </p>
        <p className="mt-4 text-base leading-[1.7] text-muted">
          The report is generated by a large language model from your answers.
          It may contain occasional errors of phrasing or emphasis. Treat it
          as a sharp practitioner observation, not as machine-perfect output.
        </p>

        <h2 className="mt-16 text-2xl font-semibold tracking-[-0.01em] text-fg">
          Engaging us for consulting
        </h2>
        <p className="mt-4 text-base leading-[1.7] text-muted">
          Consulting engagements begin with a written agreement that covers
          scope, fees, deliverables, confidentiality, and intellectual
          property. Anything published on this site about our consulting is
          marketing, not contract.
        </p>

        <h2 className="mt-16 text-2xl font-semibold tracking-[-0.01em] text-fg">
          Intellectual property
        </h2>
        <ul className="mt-4 space-y-3 text-base leading-[1.7] text-muted">
          <li>
            <span className="text-fg">Our content.</span> Site copy, the
            assessment question set, the scoring methodology, and the Archos
            Labs brand are owned by Archos Labs Pty Ltd. You may not
            reproduce, republish, or build a derivative tool from them without
            written permission.
          </li>
          <li>
            <span className="text-fg">Your content.</span> Your assessment
            answers and the resulting report are yours. We retain a copy in
            your account so you can return to it; you can request deletion at
            any time.
          </li>
        </ul>

        <h2 className="mt-16 text-2xl font-semibold tracking-[-0.01em] text-fg">
          Disclaimers
        </h2>
        <p className="mt-4 text-base leading-[1.7] text-muted">
          The site and the assessment are provided &ldquo;as is&rdquo;. We
          make no guarantees about availability, suitability for your
          situation, or specific business outcomes from acting on the report.
          You are responsible for any decisions you make based on what you
          read here.
        </p>

        <h2 className="mt-16 text-2xl font-semibold tracking-[-0.01em] text-fg">
          Limitation of liability
        </h2>
        <p className="mt-4 text-base leading-[1.7] text-muted">
          To the extent permitted by Australian law, Archos Labs Pty Ltd is
          not liable for any indirect, consequential, or special loss arising
          from your use of the site or the assessment. Nothing in these terms
          excludes or limits any consumer guarantee or right that cannot
          lawfully be excluded under the Australian Consumer Law.
        </p>

        <h2 className="mt-16 text-2xl font-semibold tracking-[-0.01em] text-fg">
          Governing law
        </h2>
        <p className="mt-4 text-base leading-[1.7] text-muted">
          These terms are governed by the laws of New South Wales, Australia.
          Any dispute will be heard in the courts of New South Wales.
        </p>

        <h2 className="mt-16 text-2xl font-semibold tracking-[-0.01em] text-fg">
          Changes to these terms
        </h2>
        <p className="mt-4 text-base leading-[1.7] text-muted">
          When we update this page, we change the &ldquo;last updated&rdquo;
          date at the top. Continued use of the site after changes means you
          accept the updated terms.
        </p>

        <h2 className="mt-16 text-2xl font-semibold tracking-[-0.01em] text-fg">
          Contact
        </h2>
        <p className="mt-4 text-base leading-[1.7] text-muted">
          Archos Labs Pty Ltd<br />
          Sydney, Australia<br />
          <a
            href="mailto:rob.angeles@archoslabs.xyz"
            className="text-accent hover:underline"
          >
            rob.angeles@archoslabs.xyz
          </a>
        </p>
      </article>
    </main>
  );
}
