// AES-256-GCM helpers for at-rest encryption of Rob's Google refresh token
// (D6a). The token lives in consultant.google_refresh_token_encrypted as a
// base64 string emitted by encrypt(), and is decoded with decrypt() on
// each Google API call.
//
// Format on disk (all base64-encoded as one string):
//   [ 12-byte IV ] [ 16-byte auth tag ] [ ciphertext bytes ]
//
// The IV is random per encrypt — uniqueness is critical for GCM security
// (reusing an IV with the same key leaks the plaintext XOR). 12 bytes is
// the GCM-recommended length; we use cryptographically secure randomBytes.
//
// The auth tag is generated by GCM during encryption and validated during
// decryption. Any tamper to ciphertext or IV → decrypt throws. We wrap
// that into a CryptoError so the route handler can emit the security
// [ALERT] email per plan §3 threat model.
//
// Key: 32 bytes, supplied via BOOKING_ENCRYPTION_KEY env var as a base64
// string. Generate one with:
//   node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"

import {
  createCipheriv,
  createDecipheriv,
  randomBytes,
  type CipherGCMTypes,
} from "node:crypto";
import { CryptoError } from "./errors/booking";

const ALGORITHM: CipherGCMTypes = "aes-256-gcm";
const IV_LENGTH = 12;
const TAG_LENGTH = 16;
const KEY_LENGTH = 32;

// Reads BOOKING_ENCRYPTION_KEY at call time (not module load) so tests
// can set the env var per-suite without import-order gymnastics.
export function getKey(): Buffer {
  const raw = process.env.BOOKING_ENCRYPTION_KEY;
  if (!raw) {
    throw new CryptoError(
      "BOOKING_ENCRYPTION_KEY env var is not set — required for Google refresh-token encryption",
    );
  }
  const key = Buffer.from(raw, "base64");
  if (key.length !== KEY_LENGTH) {
    throw new CryptoError(
      `BOOKING_ENCRYPTION_KEY must decode to ${KEY_LENGTH} bytes, got ${key.length}`,
    );
  }
  return key;
}

// Encrypt a string with AES-256-GCM. Returns a single base64 string
// holding IV || tag || ciphertext. `key` defaults to BOOKING_ENCRYPTION_KEY
// — tests pass an explicit key.
export function encrypt(plaintext: string, key: Buffer = getKey()): string {
  const iv = randomBytes(IV_LENGTH);
  const cipher = createCipheriv(ALGORITHM, key, iv);
  const ciphertext = Buffer.concat([
    cipher.update(plaintext, "utf8"),
    cipher.final(),
  ]);
  const tag = cipher.getAuthTag();
  return Buffer.concat([iv, tag, ciphertext]).toString("base64");
}

// Decrypt a string produced by encrypt(). Throws CryptoError on:
//   - malformed input (wrong length, undecodable base64),
//   - tampered ciphertext / IV / tag (GCM auth check fails),
//   - wrong key.
//
// Callers in lib/google-calendar.ts treat ANY CryptoError as a flag to
// mark consultant.google_status='stale' and emit a security alert email.
export function decrypt(blob: string, key: Buffer = getKey()): string {
  let bytes: Buffer;
  try {
    bytes = Buffer.from(blob, "base64");
  } catch (err) {
    throw new CryptoError("ciphertext is not valid base64", { cause: err });
  }
  if (bytes.length < IV_LENGTH + TAG_LENGTH) {
    throw new CryptoError(
      `ciphertext too short — expected at least ${IV_LENGTH + TAG_LENGTH} bytes, got ${bytes.length}`,
    );
  }
  const iv = bytes.subarray(0, IV_LENGTH);
  const tag = bytes.subarray(IV_LENGTH, IV_LENGTH + TAG_LENGTH);
  const ciphertext = bytes.subarray(IV_LENGTH + TAG_LENGTH);
  const decipher = createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(tag);
  try {
    return Buffer.concat([
      decipher.update(ciphertext),
      decipher.final(),
    ]).toString("utf8");
  } catch (err) {
    throw new CryptoError("decryption failed — tampered ciphertext or wrong key", {
      cause: err,
    });
  }
}
