// redirect-rules.ts — emit apex 301 redirect config for the WP source.
//
// Per D6 in the rosy-bee plan: the source has low traffic, so we don't
// build a per-URL redirect manifest. The whole robertangeles.com domain
// 301s to archoslabs.xyz/blog at the apex. Anyone landing on a deep WP
// URL gets bounced to /blog (the index) and finds the new post from there.
//
// Two output formats supported (caller picks via flag):
//   - htaccess  Apache rewrite rules (default for cPanel hosts)
//   - nginx     server-block config snippet
//
// Pure functions. Caller writes the output wherever appropriate
// (typically scripts/migrate-wp/output/redirect-{format}.conf).

export type RedirectFormat = "htaccess" | "nginx";

const TARGET_BASE = "https://archoslabs.xyz/blog";

export function buildRedirectConfig(format: RedirectFormat): string {
  switch (format) {
    case "htaccess":
      return buildHtaccess();
    case "nginx":
      return buildNginx();
  }
}

function buildHtaccess(): string {
  return [
    "# Translation Layer migration — apex 301",
    "# Generated by scripts/migrate-wp/redirect-rules.ts",
    "# Drop into the robertangeles.com .htaccess at root after WP is decommissioned.",
    "# Strips all paths and bounces to the new blog index.",
    "",
    "RewriteEngine On",
    "RewriteCond %{HTTP_HOST} ^(?:www\\.)?robertangeles\\.com$ [NC]",
    `RewriteRule ^.*$ ${TARGET_BASE} [R=301,L]`,
    "",
  ].join("\n");
}

function buildNginx(): string {
  return [
    "# Translation Layer migration — apex 301 (nginx)",
    "# Generated by scripts/migrate-wp/redirect-rules.ts",
    "# Replaces the robertangeles.com server block after WP is decommissioned.",
    "",
    "server {",
    "  listen 80;",
    "  listen 443 ssl;",
    "  server_name robertangeles.com www.robertangeles.com;",
    "",
    "  # SSL certs handled by the host (cPanel / Let's Encrypt). Adjust paths as needed.",
    "  # ssl_certificate     /etc/letsencrypt/live/robertangeles.com/fullchain.pem;",
    "  # ssl_certificate_key /etc/letsencrypt/live/robertangeles.com/privkey.pem;",
    "",
    `  return 301 ${TARGET_BASE};`,
    "}",
    "",
  ].join("\n");
}
